export const progressPhrases = [
    "It's definitely gotten better",
    "Just like I planned...",
    "Closer and closer!",
    "ALMOST DONE",
    "Yes?",
    "div:center",
    "classname='center-my-div'",
    "npm i center-div",
    "flex: div",
    "position:div-centered",
    "justify-div:center",
    "color:center",
    "align:div",
    "float:div-center",
    "background-color:center",
    "object-fit:center",
    "justify-content:div",
    "left:center;top:center",
    "visibility:center",
    "z-index:center",
    "margin:center",
    "document.div.moveToCenter()",
    "Please!",
    "align-self:please",
    "May the center be with you!",
    "Worked?",
    "This time!",
    "Now!",
    "Google more...",
    "C-E-N-T-E-R",
    "ADJakjfaljfal",
    "Impossible...",
    "I need a break",
    "let div = 'center'",
    "return div-centered ? true : true",
    "div.forEach(div => div.center())",
    "if(div !== centered) div === centered"
]